### ISSUE TITLE
Add Summary Output following Test Run

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStatsintegrationTest#1]
- [x] Add a Summary text file to your test outputs

>N points ran
>N points matched
>N points added to Library
>N points did not match

- [x] Then below a comparison for each non-matching point containing:

>Point ID
>Lat, Long
>State
>HUC
>(if true) Delineation not matched
>BCs that didn't match, and values

**Comment by tim7en** [comment]
Second assignment last two steps left, probably tomorrow. Cleaning up code as well.

**Comment by tim7en** [comment]
Added to the code
