### ISSUE TITLE
Spin up Linux EC2 for testing in StreamStats Sub-Account

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStatsintegrationTest#4]
We're looking to spin up an EC2 instance that will be used to run the StreamStats integration test.
There is little expected 'load' on this instance, the test is written in Python 2.7 and has few dependencies.

**Comment by aaronstephenson** [comment]
Sure. A few questions tho...

3. Will this need any ESRI products, either Server or Desktop or both?
2. Will the server need to run 24/7, or during business hours, or only on demand?
4. How resource-intensive will the integration test be (sustained high usage, or sporadic/burst-like usage)

This also might be a great opportunity to explore containerization, since this seems to be a very focused use with few dependencies. Or possibly even Lambda, but only if the test duration is short (on the order of seconds).

@DanielJBeckman let's work on this together when you're next available.

**Comment by DanielJBeckman** [comment]
I am available after my exam today. So 4ish.

**Comment by aaronstephenson** [comment]
Let's hold off until we get more details from the SS team.

**Comment by DanielJBeckman** [comment]
This is still in holding correct?

**Comment by aaronstephenson** [comment]
Yes, until @HansVraga or someone on the SS team can answer my previous questions above.

**Comment by HansVraga** [comment]
Wow, missed the response on this, sorry fellas. Answers:

(Interesting numbering scheme)
~3. No, but the tests do leverage ArcPy.~ Jeremy corrects me below.
4. On demand. We plan to write a script to fire up the server, run the tests, output the results, and shut it down.
5. I'll ping Jeremy on this.

**Comment by jknewson** [comment]
3) the scripts do not leverage arcpy. they are a simply calling REST services
4) yes on demand, they could run for quite a few hrs (maybe even days) depending on the number of sites we have them runing
5) probably sustained high usage, But as I mentioned in 3) they shouldn't be resources intensive (well maybe memory). It really is just a script that will loop over a n number of sites, hits other REST endpoints, then compares the response against local values stored in files.

**Comment by HansVraga** [comment]
Given your answer to #5 Jeremy, should we look for a modest-sized reserved instance rather than on-demand?

**Comment by aaronstephenson** [comment]
lol, just noticed the numbering. I think I had a longer list then cut it down without renumbering :)

So this server could potentially run for a few days, but it would only be used occasionally? Sounds like on-demand to me.

@jknewson As for instance type and sizing choices, you say that the scripts aren't resource intensive (maybe RAM), but what will user traffic look like? Will there be a lot of hits (and will they be steady or intermittent), or will there be few hits?

**Comment by HansVraga** [comment]
Very little no traffic. only a handful of individuals will have the ability to kick off a test.

**Comment by jknewson** [comment]
right, I would say only one or 2 users that will kick off the script that then load tests the services on our test/production machines

**Comment by jknewson** [comment]
maybe we just start with a smaller/medium instance, and scale if/when needed

**Comment by aaronstephenson** [comment]
Yes, this definitely sounds like a T series instance (burst-able). Thanks!

**Comment by DanielJBeckman** [comment]
So here is what I did. I built this guy out with Python and bunch helpful server components. I added a ultra lightweight GUI (LXDE-core w/tightvncserver). This is to make it easier to test server tasks on a local port like you have on a windows system.  It's at least as fast as a standard Win OS and we can tweak it to make it faster.

**Comment by DanielJBeckman** [comment]
Up and running.
